web/proposals/urls.py
from django.urls import path
from . import views

app_name = 'proposals'

urlpatterns = [
	path('', views.ProposalListView.as_view(), name='home'),

    path('create', views.ProposalCreateView.as_view(), name='create_proposal'),
    path('update/<slug:proposal>/', views.ProposalUpdateView.as_view(), name='update_proposal'),
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
]

web/pyconng/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] 

web/proposals/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.template.defaultfilters import slugify


# Create your models here.

class Proposal(models.Model):

    CATEGORIES = (
        ('TT', 'Tutorial'),
        ('ST', 'Short Talk'),
        ('LT', 'Long Talk'),
    )

    AUDIENCE = (
        ('B', 'Beginners'),
        ('I', 'Intermediate'),
        ('A', 'Advanced'),
        ('E', 'Everybody'),
    )

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='proposals')
    title = models.CharField(max_length=250, blank=False, null=False, help_text='a short title of your talk')
    slug = models.SlugField(max_length=255, blank=False, null=False)
    category = models.CharField(max_length=2, choices=CATEGORIES, blank=False, null=False, help_text='Where does your talk fit in?')
    abstract = models.TextField(blank=False, null=False, help_text='a summary on why this talk is neccessary')
    description = models.TextField(blank=False, null=False, help_text='content of your talk as to be shown to the public')
    pre_requesite = models.TextField(blank=True, null=True, help_text='what are the pre-requisites for this talk?')
    audience = models.CharField(max_length=2, choices=AUDIENCE, default='E', help_text='Who are your target audience?')
    about_author = models.TextField(blank=False, null=False, help_text='Let us know a little more about you')
    website = models.URLField(blank=True, null=True, help_text='have a link to your personal website/blog?')
    #profile_picture = models.ImageField(upload_to = 'pic_folder/', help_text='a nice image of you')
    submitted = models.DateTimeField(default=timezone.now)
    last_updated = models.DateTimeField(auto_now_add=True)
    accepted = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
    	self.slug = slugify(self.title)
    	super(Proposal, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

web/proposals/forms.py
from django import forms
from .models import Proposal


class ProposalForm(forms.ModelForm):
    class Meta:
        model = Proposal
        exclude = ('accepted', 'author','slug', 'submitted')

web/proposals/views.py
from django.shortcuts import render
from .forms import ProposalForm
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.views.generic.list import ListView
from django.shortcuts import reverse

from .models import Proposal

class ProposalListView(LoginRequiredMixin, ListView):

	 model = Proposal
	 template_name = 'proposals/proposals.html'

	 def get_queryset(self):
	 	return self.request.user.proposals.all()


class ProposalCreateView(LoginRequiredMixin, CreateView):
    template_name = 'proposals/create_proposal.html'
    form_class = ProposalForm
    success_url = 'thanks'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.instance.author = self.request.user
        return super().form_valid(form)


class ProposalUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'proposals/create_proposal.html'
    form_class = ProposalForm
    model = Proposal
    slug_field = 'slug'
    slug_url_kwarg = 'proposal'
    success_url = '../../thanks'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        #form.instance.created_by = self.request.user
        return super().form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        """ Making sure that only authors can update their proposals """
        obj = self.get_object()
        if obj.author != self.request.user:
            return HttpResponseForbidden()
        return super(ProposalUpdateView, self).dispatch(request, *args, **kwargs)

class ThanksView(TemplateView):
	template_name = 'proposals/thanks.html'

web/templates/proposals/create_proposal.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Submit a Proposal{% endblock %}



{% block content %}
<div class="container-fluid" style="margin-top: 100px">
<h2 class="d-flex justify-content-center">Submit a Proposal</h2>
<div class="d-flex justify-content-center">

<form role="form" class="form-horizontal" method="post">
  {% csrf_token %}
  <div class="form-group">
  {{ form |crispy}}
  <input type="submit" class="btn btn-success" value="Submit Proposal">
</div>
</form>
</div>
</div>

</div>

{% endblock %}

web/templates/proposals/proposals.html
{% extends 'base.html' %}

<section id="speakers" class="wow fadeInUp">
    
{%if object_list %}<h1>Your Submited Proposals</h1>{%endif%}

{% block content%}
<div class="container" style="margin-top: 132px">
    <div class="row">    
        {% for proposal in object_list%}
        <div class="col-md-8 mx-auto">
            <a href="{% url 'proposals:update_proposal' proposal.slug %}" title="">
                <b>{{proposal.title}}</b>
            </a> <i>Approval pending</i><br>
            {% empty %}
            <h2>You have not submitted any proposals yet.</h2>
        </div>
        <div class="col">
            <b><a href="{% url 'proposals:create_proposal' %}">Submit a Proposal?</a></b>
            {%endfor%}
        </div>
    </div>
</div>
{% endblock content%}

</section>

web/templates/proposals/thanks.html
{% extends 'base.html' %}
<section id="speakers" class="wow fadeInUp">
{% block content%}
<div class="cont">

<div class="align-items-center">
Thanks For submitting you talk. You will recieve an email notification once your talk is approved
<p><b><a href="{% url 'proposals:create_proposal'%}"></a>
Submit Another Talk?</a></b></p>
</div>


</div>
{% endblock content%}
</section>